version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: sofikash/kittygram_final-backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: sofikash/kittygram_final-frontend:latest 
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/ 
  gateway:
    image: sofikash/kittygram_final-gateway:latest
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
